gsap.registerPlugin(ScrollTrigger);let _navReady=false;document.addEventListener('DOMContentLoaded',()=>{initLenis();initMobileNav();initPageTransition();initNavReveal();initNavScroll();initSingleHero();initWorksHero();initServiceHeroScroll();initServiceHeroReveal();initServiceReveal();initAboutReveal();initAboutCardsReveal();initContactReveal();initHeroReveal();initShowreelExpansion();initWorksReveal();initCirclesAnimation();initSectionFadeUps();initServicesReveal();initFooterSymbol();});function initLenis(){const lenis=new Lenis({duration:1.0,easing:(t)=>1-Math.pow(1-t,3),smoothWheel:true,wheelMultiplier:1,touchMultiplier:2,});lenis.on('scroll',ScrollTrigger.update);gsap.ticker.add((time)=>{lenis.raf(time*1000);});gsap.ticker.lagSmoothing(0);}
function initHeroReveal(){const lines=document.querySelectorAll('.headline__inner');if(!lines.length)return;gsap.set(lines,{y:'105%'});gsap.to(lines,{y:'0%',duration:1,stagger:0.12,ease:'power3.out',delay:0.2,});const label=document.querySelector('.label-text');if(label){gsap.from(label,{y:12,opacity:0,duration:0.8,ease:'power2.out',delay:0.1,});}}
function initWorksReveal(){const items=document.querySelectorAll('.js-works-item');if(!items.length)return;gsap.from(items,{y:40,opacity:0,duration:0.9,stagger:0.15,ease:'power2.out',scrollTrigger:{trigger:'.works-grid',start:'top 75%',},});}
function initCirclesAnimation(){const circleLeft=document.querySelector('.js-circle-left');const circleRight=document.querySelector('.js-circle-right');if(!circleLeft||!circleRight)return;const CENTER_X=122.5;gsap.set([circleLeft,circleRight],{x:CENTER_X});const tl=gsap.timeline({paused:true,defaults:{duration:1.2,ease:'power2.inOut'},});tl.to(circleLeft,{x:0},0).to(circleRight,{x:245},0);ScrollTrigger.create({trigger:'.services-decoration',start:'top bottom',end:'bottom top',onEnter:()=>tl.play(),onLeaveBack:()=>tl.reverse(),onLeave:()=>tl.reverse(),onEnterBack:()=>tl.play(),});}
function initShowreelExpansion(){const hero=document.querySelector('.js-hero');const card=document.querySelector('.js-showreel-card');const heroBody=document.querySelector('.js-hero-body');const video=document.querySelector('.showreel-video');if(video){const playPromise=video.play();if(playPromise!==undefined){playPromise.catch(()=>{document.addEventListener('click',()=>video.play(),{once:true});document.addEventListener('touchstart',()=>video.play(),{once:true});});}}
if(window.innerWidth<=1024)return;if(!hero||!card)return;const CARD_RIGHT=window.__CARD_RIGHT||44;const CARD_TOP=40;const CARD_W=600;const CARD_H=338;gsap.set(card,{transformOrigin:'left top'});if(video){gsap.set(video,{transformOrigin:'50% 50%'});}
const tl=gsap.timeline({scrollTrigger:{id:'showreel-pin',trigger:hero,start:'top top',end:'+=50%',pin:true,pinSpacing:true,scrub:1.5,anticipatePin:1,invalidateOnRefresh:true,},});tl.to(card,{x:()=>-(window.innerWidth-CARD_RIGHT-CARD_W),y:-CARD_TOP,scaleX:()=>window.innerWidth/CARD_W,scaleY:()=>window.innerHeight/CARD_H,borderRadius:0,ease:'none',},0);if(video){tl.to(video,{scaleX:()=>Math.max(1,(window.innerHeight*CARD_W/CARD_H)/window.innerWidth),scaleY:()=>Math.max(1,(window.innerWidth*CARD_H/CARD_W)/window.innerHeight),ease:'none',},0);}
if(heroBody){tl.to(heroBody,{opacity:0,ease:'none',duration:0.5,},0);}
tl.to({},{duration:.5});window.addEventListener('load',()=>ScrollTrigger.refresh());let rafId;window.addEventListener('resize',()=>{cancelAnimationFrame(rafId);rafId=requestAnimationFrame(()=>ScrollTrigger.refresh());});}
function initSectionFadeUps(){const targets=document.querySelectorAll('.section-featured-works .section-header, .section-services .section-header, .services-headline');targets.forEach((el)=>{gsap.from(el,{y:24,opacity:0,duration:1,ease:'power2.out',scrollTrigger:{trigger:el,start:'top 80%',},});});}
function initServicesReveal(){const items=document.querySelectorAll('.services-item');if(!items.length)return;gsap.from(items,{y:20,opacity:0,duration:0.6,stagger:0.1,ease:'power2.out',scrollTrigger:{trigger:'.services-list',start:'top 75%',},});}
function initPageTransition(){const overlay=document.querySelector('.page-transition');if(!overlay)return;function fadeOut(){gsap.fromTo(overlay,{autoAlpha:1},{autoAlpha:0,duration:0.6,ease:'power2.out',delay:0.1});}
fadeOut();window.addEventListener('pagehide',()=>{gsap.set(overlay,{autoAlpha:1});});window.addEventListener('pageshow',(e)=>{if(e.persisted)fadeOut();});document.querySelectorAll('a[href]').forEach((link)=>{const href=link.getAttribute('href')||'';if(link.hostname!==window.location.hostname||link.target==='_blank'||link.href===window.location.href||href.startsWith('#'))return;link.addEventListener('click',(e)=>{if(e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;if(e.button!==0)return;e.preventDefault();const dest=link.href;gsap.to(overlay,{autoAlpha:1,duration:0.45,ease:'power2.in',onComplete:()=>{window.location.href=dest;},});});});}
function initNavReveal(){const nav=document.querySelector('.site-nav');const filterNav=document.querySelector('.works-filter-nav');if(!nav)return;const NAV_TOP=40;const isMobile=window.innerWidth<=1024;gsap.set(nav,{y:-(NAV_TOP+nav.offsetHeight),autoAlpha:0});if(filterNav&&!isMobile){gsap.set(filterNav,{y:-(NAV_TOP+filterNav.offsetHeight),autoAlpha:0});}
gsap.to(nav,{y:0,autoAlpha:1,duration:1,ease:'power3.out',delay:0.2,onComplete:()=>{_navReady=true;},});if(filterNav&&!isMobile){gsap.to(filterNav,{y:0,autoAlpha:1,duration:1,ease:'power3.out',delay:0.2,});}
document.querySelectorAll('a[href]').forEach((link)=>{const href=link.getAttribute('href')||'';if(link.hostname!==window.location.hostname||link.target==='_blank'||link.href===window.location.href||href.startsWith('#'))return;link.addEventListener('click',(e)=>{if(e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;if(e.button!==0)return;gsap.to(nav,{y:-(NAV_TOP+nav.offsetHeight),autoAlpha:0,duration:0.35,ease:'power2.in',});if(filterNav&&!isMobile){gsap.to(filterNav,{y:-(NAV_TOP+filterNav.offsetHeight),autoAlpha:0,duration:0.35,ease:'power2.in',});}});});window.addEventListener('pageshow',(e)=>{if(!e.persisted)return;_navReady=false;gsap.set(nav,{y:-(NAV_TOP+nav.offsetHeight),autoAlpha:0});if(filterNav&&!isMobile){gsap.set(filterNav,{y:-(NAV_TOP+filterNav.offsetHeight),autoAlpha:0});}
gsap.to(nav,{y:0,autoAlpha:1,duration:1,ease:'power3.out',delay:0.2,onComplete:()=>{_navReady=true;},});if(filterNav&&!isMobile){gsap.to(filterNav,{y:0,autoAlpha:1,duration:1,ease:'power3.out',delay:0.2,});}});}
function initNavScroll(){if(window.innerWidth<=980)return;const nav=document.querySelector('.site-nav');const menu=document.querySelector('.nav-menu');const panel=document.querySelector('.nav-main-panel');const contact=document.querySelector('.nav-contact');if(!nav||!menu)return;const FULL_H=120;const SMALL_H=60;const MENU_H=menu.offsetHeight;let isScrolled=false;let isHovered=false;function toSmall(dur=0.45){if(!_navReady)return;gsap.killTweensOf([nav,contact,panel,menu].filter(Boolean));gsap.to(nav,{height:SMALL_H,duration:dur,ease:'power2.inOut'});if(contact)gsap.to(contact,{height:SMALL_H,duration:dur,ease:'power2.inOut'});gsap.to(panel,{paddingTop:19,paddingBottom:19,duration:dur,ease:'power2.inOut'});gsap.to(menu,{opacity:0,height:0,pointerEvents:'none',duration:dur*0.8,ease:'power2.in'});}
function toFull(dur=0.45){if(!_navReady)return;gsap.killTweensOf([nav,contact,panel,menu].filter(Boolean));gsap.to(nav,{height:FULL_H,duration:dur,ease:'power2.out'});if(contact)gsap.to(contact,{height:FULL_H,duration:dur,ease:'power2.out'});gsap.to(panel,{paddingTop:20,paddingBottom:20,duration:dur,ease:'power2.out'});gsap.to(menu,{opacity:1,height:MENU_H,pointerEvents:'auto',duration:dur,ease:'power2.out'});}
function checkScroll(){const scrolled=window.scrollY>50;if(scrolled===isScrolled)return;isScrolled=scrolled;if(isScrolled&&!isHovered)toSmall();if(!isScrolled)toFull();}
window.addEventListener('scroll',checkScroll,{passive:true});gsap.delayedCall(1.3,checkScroll);nav.addEventListener('mouseenter',()=>{if(!isScrolled)return;isHovered=true;toFull(0.35);});nav.addEventListener('mouseleave',()=>{if(!isScrolled)return;isHovered=false;toSmall(0.35);});window.addEventListener('pageshow',(e)=>{if(!e.persisted)return;isScrolled=false;isHovered=false;gsap.delayedCall(1.3,checkScroll);});}
function initSingleHero(){const heroImg=document.querySelector('.portfolio-hero__img');if(!heroImg)return;const title=document.querySelector('.portfolio-title');const excerpt=document.querySelector('.portfolio-excerpt');const metas=Array.from(document.querySelectorAll('.portfolio-meta__item'));const btn=document.querySelector('.portfolio-hero__btn');const textTargets=[title,excerpt,...metas,btn].filter(Boolean);gsap.set(heroImg,{clipPath:'inset(0 0 100% 0)',scale:1.2});if(textTargets.length){gsap.set(textTargets,{y:16,opacity:0});}
gsap.to(heroImg,{clipPath:'inset(0 0 0% 0)',scale:1,duration:2,delay:.2,ease:Quint.easeOut,});if(textTargets.length){gsap.to(textTargets,{y:0,opacity:1,duration:1,stagger:0.2,ease:'power2.out',delay:1,});}}
function initWorksHero(){const hero=document.querySelector('.works-hero');if(!hero)return;const label=hero.querySelector('.works-hero__label');const headline=hero.querySelector('.works-hero__headline');const textTargets=[label,headline].filter(Boolean);if(textTargets.length){gsap.set(textTargets,{y:16,opacity:0});}
if(textTargets.length){gsap.to(textTargets,{y:0,opacity:1,duration:1,stagger:0.2,ease:'power2.out',});}}
function initServiceHeroReveal(){const titleArea=document.querySelector('.service-hero__title-area');if(!titleArea)return;const targets=[titleArea.querySelector('.service-hero__label'),titleArea.querySelector('.service-hero__h1'),titleArea.querySelector('.service-hero__sub'),].filter(Boolean);if(!targets.length)return;gsap.from(targets,{y:16,opacity:0,duration:1,stagger:0.2,ease:'power2.out',delay:0.3,});}
function initServiceHeroScroll(){const imgs=document.querySelector('.js-service-imgs');if(!imgs)return;gsap.to(imgs,{x:()=>-(imgs.scrollWidth-window.innerWidth),ease:'none',scrollTrigger:{trigger:'.service-hero',start:'top top',end:'bottom top',scrub:1,invalidateOnRefresh:true,},});}
function initServiceReveal(){const items=document.querySelectorAll('.js-service-item');if(!items.length)return;items.forEach((item)=>{const targets=[item.querySelector('.service-item__num'),item.querySelector('.section-line'),item.querySelector('.service-item__title'),...Array.from(item.querySelectorAll('.service-item__descs p')),item.querySelector('.service-item__featured'),...Array.from(item.querySelectorAll('.service-tag')),].filter(Boolean);if(!targets.length)return;gsap.from(targets,{y:20,opacity:0,duration:0.7,stagger:0.07,ease:'power2.out',scrollTrigger:{trigger:item,start:'top 78%',},});});}
function initAboutReveal(){const titleArea=document.querySelector('.about-hero__title-area');if(!titleArea)return;const targets=[titleArea.querySelector('.about-hero__label'),titleArea.querySelector('.about-hero__h1'),...Array.from(titleArea.querySelectorAll('.about-hero__sub p')),].filter(Boolean);if(!targets.length)return;gsap.from(targets,{y:16,opacity:0,duration:1,stagger:0.2,ease:'power2.out',delay:0.3,});}
function initAboutCardsReveal(){const cards=document.querySelectorAll('.js-about-card');if(!cards.length)return;gsap.from(cards,{y:30,opacity:0,duration:0.8,stagger:0.1,ease:'power2.out',scrollTrigger:{trigger:'.about-hero__cards',start:'top 80%',},});}
function initFooterSymbol(){const circles=document.querySelectorAll('.js-footer-circle');if(circles.length<4)return;const startOffsets=[0,-66.88,-167.00,-263.25];gsap.set(circles,{x:(i)=>startOffsets[i]});const tl=gsap.timeline({paused:true});tl.to(circles,{x:0,duration:0.9,stagger:0.1,ease:'power3.out',});ScrollTrigger.create({trigger:'.site-footer',start:'top 90%',end:'bottom top',onEnter:()=>tl.play(),onLeaveBack:()=>tl.reverse(),onLeave:()=>tl.reverse(),onEnterBack:()=>tl.play(),});}
function initMobileNav(){const hamburger=document.querySelector('.nav-hamburger');const nav=document.querySelector('.site-nav');const mobileMenu=document.querySelector('.nav-mobile-menu');if(!hamburger||!nav||!mobileMenu)return;if(window.innerWidth>980)return;const NAV_CLOSED_H=60;function openMenu(){hamburger.classList.add('is-open');hamburger.setAttribute('aria-expanded','true');mobileMenu.setAttribute('aria-hidden','false');gsap.to(nav,{height:'auto',duration:0.4,ease:'power2.out'});}
function closeMenu(){hamburger.classList.remove('is-open');hamburger.setAttribute('aria-expanded','false');mobileMenu.setAttribute('aria-hidden','true');gsap.to(nav,{height:NAV_CLOSED_H,duration:0.3,ease:'power2.in'});}
hamburger.addEventListener('click',()=>{hamburger.classList.contains('is-open')?closeMenu():openMenu();});mobileMenu.querySelectorAll('a').forEach(link=>{link.addEventListener('click',closeMenu);});}
function initContactReveal(){const titleArea=document.querySelector('.contact-hero__title-area');if(!titleArea)return;const targets=[titleArea.querySelector('.contact-hero__label'),titleArea.querySelector('.contact-hero__h1'),].filter(Boolean);if(!targets.length)return;gsap.from(targets,{y:16,opacity:0,duration:1,stagger:0.2,ease:'power2.out',delay:0.3,});}