gsap.registerPlugin(ScrollTrigger);let _navReady=false;document.addEventListener('DOMContentLoaded',()=>{initLenis();initPageTransition();initNavReveal();initNavScroll();initHeroReveal();initShowreelExpansion();});function initLenis(){const lenis=new Lenis({duration:1.0,easing:(t)=>1-Math.pow(1-t,3),smoothWheel:true,wheelMultiplier:1,touchMultiplier:2,});lenis.on('scroll',ScrollTrigger.update);gsap.ticker.add((time)=>{lenis.raf(time*1000);});gsap.ticker.lagSmoothing(0);}
function initHeroReveal(){const lines=document.querySelectorAll('.headline__inner');if(!lines.length)return;gsap.set(lines,{y:'105%'});gsap.to(lines,{y:'0%',duration:1,stagger:0.12,ease:'power3.out',delay:0.2,});}
function initShowreelExpansion(){const hero=document.querySelector('.js-hero');const card=document.querySelector('.js-showreel-card');const heroBody=document.querySelector('.js-hero-body');if(window.innerWidth<=1024)return;if(!hero||!card)return;const CARD_RIGHT=window.__CARD_RIGHT||44;const CARD_TOP=40;const CARD_W=600;const CARD_H=338;gsap.set(card,{transformOrigin:'left top'});
const tl=gsap.timeline({scrollTrigger:{id:'showreel-pin',trigger:hero,start:'top top',end:'+=50%',pin:true,pinSpacing:true,scrub:1.5,anticipatePin:1,invalidateOnRefresh:true,},});tl.to(card,{x:()=>-(window.innerWidth-CARD_RIGHT-CARD_W),y:-CARD_TOP,scaleX:()=>window.innerWidth/CARD_W,scaleY:()=>window.innerHeight/CARD_H,borderRadius:0,ease:'none',},0);
if(heroBody){tl.to(heroBody,{opacity:0,ease:'none',duration:0.5,},0);}
tl.to({},{duration:.5});window.addEventListener('load',()=>ScrollTrigger.refresh());let rafId;window.addEventListener('resize',()=>{cancelAnimationFrame(rafId);rafId=requestAnimationFrame(()=>ScrollTrigger.refresh());});}
function initPageTransition(){const overlay=document.querySelector('.page-transition');if(!overlay)return;function fadeOut(){gsap.fromTo(overlay,{autoAlpha:1},{autoAlpha:0,duration:0.6,ease:'power2.out',delay:0.1});}
fadeOut();window.addEventListener('pagehide',()=>{gsap.set(overlay,{autoAlpha:1});});window.addEventListener('pageshow',(e)=>{if(e.persisted)fadeOut();});document.querySelectorAll('a[href]').forEach((link)=>{const href=link.getAttribute('href')||'';if(link.hostname!==window.location.hostname||link.target==='_blank'||link.href===window.location.href||href.startsWith('#'))return;link.addEventListener('click',(e)=>{if(e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;if(e.button!==0)return;e.preventDefault();const dest=link.href;gsap.to(overlay,{autoAlpha:1,duration:0.45,ease:'power2.in',onComplete:()=>{window.location.href=dest;},});});});}
function initNavReveal(){const nav=document.querySelector('.site-nav');const filterNav=document.querySelector('.works-filter-nav');if(!nav)return;const NAV_TOP=40;const isMobile=window.innerWidth<=1024;gsap.set(nav,{y:-(NAV_TOP+nav.offsetHeight),autoAlpha:0});if(filterNav&&!isMobile){gsap.set(filterNav,{y:-(NAV_TOP+filterNav.offsetHeight),autoAlpha:0});}
gsap.to(nav,{y:0,autoAlpha:1,duration:1,ease:'power3.out',delay:0.2,onComplete:()=>{_navReady=true;},});if(filterNav&&!isMobile){gsap.to(filterNav,{y:0,autoAlpha:1,duration:1,ease:'power3.out',delay:0.2,});}
document.querySelectorAll('a[href]').forEach((link)=>{const href=link.getAttribute('href')||'';if(link.hostname!==window.location.hostname||link.target==='_blank'||link.href===window.location.href||href.startsWith('#'))return;link.addEventListener('click',(e)=>{if(e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;if(e.button!==0)return;gsap.to(nav,{y:-(NAV_TOP+nav.offsetHeight),autoAlpha:0,duration:0.35,ease:'power2.in',});if(filterNav&&!isMobile){gsap.to(filterNav,{y:-(NAV_TOP+filterNav.offsetHeight),autoAlpha:0,duration:0.35,ease:'power2.in',});}});});window.addEventListener('pageshow',(e)=>{if(!e.persisted)return;_navReady=false;gsap.set(nav,{y:-(NAV_TOP+nav.offsetHeight),autoAlpha:0});if(filterNav&&!isMobile){gsap.set(filterNav,{y:-(NAV_TOP+filterNav.offsetHeight),autoAlpha:0});}
gsap.to(nav,{y:0,autoAlpha:1,duration:1,ease:'power3.out',delay:0.2,onComplete:()=>{_navReady=true;},});if(filterNav&&!isMobile){gsap.to(filterNav,{y:0,autoAlpha:1,duration:1,ease:'power3.out',delay:0.2,});}});}
function initNavScroll(){if(window.innerWidth<=980)return;const nav=document.querySelector('.site-nav');const menu=document.querySelector('.nav-menu');const panel=document.querySelector('.nav-main-panel');const contact=document.querySelector('.nav-contact');if(!nav||!menu)return;const FULL_H=120;const SMALL_H=60;const MENU_H=menu.offsetHeight;let isScrolled=false;let isHovered=false;function toSmall(dur=0.45){if(!_navReady)return;gsap.killTweensOf([nav,contact,panel,menu].filter(Boolean));gsap.to(nav,{height:SMALL_H,duration:dur,ease:'power2.inOut'});if(contact)gsap.to(contact,{height:SMALL_H,duration:dur,ease:'power2.inOut'});if(panel)gsap.to(panel,{paddingTop:19,paddingBottom:19,duration:dur,ease:'power2.inOut'});gsap.to(menu,{opacity:0,height:0,pointerEvents:'none',duration:dur*0.8,ease:'power2.in'});}
function toFull(dur=0.45){if(!_navReady)return;gsap.killTweensOf([nav,contact,panel,menu].filter(Boolean));gsap.to(nav,{height:FULL_H,duration:dur,ease:'power2.out'});if(contact)gsap.to(contact,{height:FULL_H,duration:dur,ease:'power2.out'});if(panel)gsap.to(panel,{paddingTop:20,paddingBottom:20,duration:dur,ease:'power2.out'});gsap.to(menu,{opacity:1,height:MENU_H,pointerEvents:'auto',duration:dur,ease:'power2.out'});}
function checkScroll(){const scrolled=window.scrollY>50;if(scrolled===isScrolled)return;isScrolled=scrolled;if(isScrolled&&!isHovered)toSmall();if(!isScrolled)toFull();}
window.addEventListener('scroll',checkScroll,{passive:true});gsap.delayedCall(1.3,checkScroll);nav.addEventListener('mouseenter',()=>{if(!isScrolled)return;isHovered=true;toFull(0.35);});nav.addEventListener('mouseleave',()=>{if(!isScrolled)return;isHovered=false;toSmall(0.35);});window.addEventListener('pageshow',(e)=>{if(!e.persisted)return;isScrolled=false;isHovered=false;gsap.delayedCall(1.3,checkScroll);});}
